# Generated by Django 4.2.2 on 2023-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_concert_organizername'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='bannerImg',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
