# Generated by Django 4.2.2 on 2023-09-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_user_birthplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='eventDue',
            field=models.DateTimeField(null=True),
        ),
    ]
