# Generated by Django 4.2.2 on 2023-09-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='expiration',
            field=models.TimeField(null=True),
        ),
    ]
