# Generated by Django 4.2.2 on 2023-09-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_resetpassword_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='eventDue',
        ),
    ]
