# Generated by Django 4.2.2 on 2023-09-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_concert_createdat_remove_concert_eventdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='eventDue',
            field=models.DateTimeField(null=True),
        ),
    ]
