# Generated by Django 4.2.2 on 2023-09-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_ticket_expiration_ticket_datevalidrange1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='bannerImg',
            field=models.ImageField(default='concert_banners/default.jpg', null=True, upload_to='concert_banners'),
        ),
    ]
