# Generated by Django 4.2.2 on 2023-09-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_concert_bannerimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='eventDue',
        ),
        migrations.AddField(
            model_name='concert',
            name='dateValidRange1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='dateValidRange2',
            field=models.DateField(null=True),
        ),
    ]
