# Generated by Django 4.2.2 on 2023-09-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_tickettype_remove_ticket_datevalidrange1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dateValidRange1',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dateValidRange2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketType',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'Vip')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
