# Generated by Django 4.2.2 on 2023-09-25 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_ticket_datevalidrange1_ticket_datevalidrange2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('price', models.IntegerField(null=True)),
                ('dateValidRange1', models.DateField(null=True)),
                ('dateValidRange2', models.DateField(null=True)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='dateValidRange1',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='dateValidRange2',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tickettype'),
        ),
    ]
