# Generated by Django 4.2.2 on 2023-10-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_concert_organizername_alter_ticket_boughtby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='limit',
        ),
    ]
