# Generated by Django 4.2.2 on 2023-10-16 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_concert_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='organizerName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
