# Generated by Django 4.2.2 on 2023-10-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_tickettype_address_tickettype_city_tickettype_postal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='province',
        ),
        migrations.AddField(
            model_name='concert',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='postal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
