# Generated by Django 4.2.2 on 2023-10-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_tickettype_address_remove_tickettype_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='boughtBy',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
