# Generated by Django 4.2.3 on 2023-07-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_birthday_user_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
