# Generated by Django 4.2.3 on 2023-07-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_birthplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(choices=[(500, 'Standard'), (800, 'Premium')])),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='birthplace',
            field=models.DateField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticket', models.ManyToManyField(to='api.ticket')),
            ],
        ),
    ]
