# Generated by Django 4.2.3 on 2023-07-09 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_ticket_date_created_ticket_expiration_ticket_isused'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='boughtBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
