# Generated by Django 4.2.2 on 2023-08-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_concert_bannerimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='paragraph',
            field=models.TextField(null=True),
        ),
    ]
