# Generated by Django 4.2.2 on 2023-08-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_concert_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthplace',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
