version: "2.21"

services:
  backend:
    container_name: backend
    build: ./backend
    environment:
      - ISDEBUG=false
      - SECRETKEY=talipapa
    command: gunicorn concert_ticket.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - REACT_APP_API_URL=206.189.38.17
      - REACT_APP_API_PORT=8000
    ports:
      - 80:3000
    depends_on:
      - backend
