version: '2.21'

services:
  backend:
    build: ./backend
    container_name: backend
    env_file: variables.env
    volumes:
      - serverstatic:/backend/static
    expose:
      - 8000
  nginx:
    build: ./nginx
    container_name: nginx
    env_file:
      - variables.env
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - serverstatic:/home/app/staticfiles
  frontend:
    build: ./frontend
    container_name: frontend
    env_file: variables.env
    ports:
      - 3000:3000
    depends_on:
      - nginx
volumes:
  serverstatic:
