# Generated by Django 4.2.3 on 2023-07-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthplace',
            field=models.DateField(null=True),
        ),
    ]
