# Generated by Django 4.2.3 on 2023-07-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ticket_alter_user_birthplace_concert'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketType',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'Vip')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
