# Generated by Django 4.2.3 on 2023-07-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ticket_tickettype_alter_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='expiration',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='isUsed',
            field=models.BooleanField(default=False),
        ),
    ]
