# Generated by Django 4.2.3 on 2023-07-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ticket_boughtby'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='limit',
            field=models.IntegerField(null=True),
        ),
    ]
