# Generated by Django 4.2.2 on 2023-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_concert_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('organizer', 'Organizer'), ('normal user', 'Normal User')], max_length=100, null=True),
        ),
    ]
