# Generated by Django 4.2.2 on 2023-07-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
        migrations.AddField(
            model_name='user',
            name='isOrganizer',
            field=models.BooleanField(default=False),
        ),
    ]
